### ISSUE TITLE
bav's bank data is outdated

### ISSUE THREAD

**Issue by henriquemoody** [bav-php/bav#19]
I'm running bav from [Respect\Validation](https://github.com/Respect/Validation).

After Respect/Validation#188 I made some improvements (Respect/Validation#248, Respect/Validation#249 and Respect/Validation#250).  Now we just [create an instance of `malkusch\bav\BAV()`](https://github.com/Respect/Validation/blob/master/library/Rules/Locale/GermanBank.php#L27-L29) on our [tests](https://github.com/Respect/Validation/blob/master/tests/Rules/Locale/GermanBankTest.php#L20-L25) to ensure we have an instance to use, even though I'm getting this message:

> PHP Warning:  bav's bank data is outdated. Update the data with e.g. bin/bav-update.php in vendor/malkusch/bav/classes/dataBackend/update/LogUpdatePlan.php on line 24

After I did run `php vendor/bin/bav-update.php` the message is gone but I think this message should not appear unless you really use the library, not just when you create the object instance.

**Comment by malkusch** [comment]
Hi and thank you for your feedback. I understand that this warning is something one doesn't want in a test. In a CI this shouldn't be an issue, as building would trigger downloading a new bank file.
But in the case vendor/malkusch/bav is old (like it is probably in your local working environment) this warning is annoying. Well I'm sorry that I missed that part in the PR. I did forget about it myself.

As a local fix on your side I suggest setting no `UpdatePlan`:

```php
\malkusch\bav\ConfigurationRegistry::getConfiguration()->setUpdatePlan(null);
```
I don't recommend disabling it in general, as users won't know that they are using an outdated bank data file.

Regarding your suggestion of moving that check: I don't agree on that. I see the instantiation as the perfect place for such a task. Furthermore instantiation of `BAV` can be considered as a 	declaration of intent using it.

What do you think?

**Comment by henriquemoody** [comment]
Actually I'm having this problem on [Travis](https://travis-ci.org/Respect/Validation/jobs/49220352#L163) because I'm [caching the `vendor/` directory](https://github.com/Respect/Validation/blob/master/.travis.yml#L15-L17) in order to make the build faster - and it really works.

You're right about _instantiation of `BAV` can be considered as a declaration of intent using it_, them it also makes sense to me, but also I see two scenarios besides testing.

- I have a production environment, then I will ignore `E_USER_WARNING`
- I have a production environment, then I will not ignore `E_USER_WARNING`, so, depending on my configuration, I can have many of notifications because that and, depending on my configuration also, PagerDuty wakes me up at 03:00 AM.

That's why I don't think a good idea to make it in runtime, but it's just my opinion.

Tomorrow I will try your recommendation on Respect\Validation and also I will take a more accurate look on this constructor, it usually runs 30 seconds more than normal at first run and some times get HTTP errors from bundesbank.de. Besides the fact my servers doesn't usually have external internet access, seems to much to do in a constructor, IMO.

**Comment by henriquemoody** [comment]
Hey, @malkusch, I did what you recommended with the `\malkusch\bav\ConfigurationRegistry::getConfiguration()->setUpdatePlan(null)` but I'm getting some errors here, see:

https://travis-ci.org/Respect/Validation/jobs/85974835
Respect/Validation#556

Is there a way to disable this update for good?

**Comment by henriquemoody** [comment]
Not fixed, but I'm closing this :)
