### ISSUE TITLE
Fatal error: Class 'malkusch\index\FixedSizeIndex' not found in (...)/malkusch/bav/classes/dataBackend/file/FileDataBackend.php on line 59

### ISSUE THREAD

**Issue by Fuchur84** [bav-php/bav#21]
Hello :),

I do not know exactly if this is a fault of the autoloader, my installation or something else, but there seems to be a class missing. I can not find a file called "FixedSizeIndex.php" (or something) in the ZIP-file I downloaded neighter... am I doing something wrong?

See you
*Fuchur*

**Comment by malkusch** [comment]
Well that's why I suggested to use composer. You're missing a dependency. Get [php-index](https://github.com/malkusch/php-index).
